### ISSUE TITLE
Outline font doesnt look good

### ISSUE THREAD

**Issue by 80prozent** [awayfl/awayfl.org#1]
On my screen the outline font used for ` Get Started` `Github` and `Documentation` doesnt look really nice.

Looks a bit like bad AA.

best just use other font there

**Comment by nanjizal** [comment]
This was really fiddly but does this look acceptable.
<img width="1029" alt="awayHero" src="https://user-images.githubusercontent.com/20134338/106016509-71d50680-60b7-11eb-94b4-036cba45e8ec.png">
added to my other pull request.
