### ISSUE TITLE
Replace white background with dark grey

### ISSUE THREAD

**Issue by rob-bateman** [awayfl/awayfl.org#2]
Currently the fade between black and white with the page scroll feels a bit jarring.

As dark mode seems to be the preference for most people, the css could be updated to have white text on a dark grey background.

**Comment by nanjizal** [comment]
Was trying to work out exactly how you wanted it.  I tried a more github style black ( slight corner gradient ). The base-color seems to be the indicator blue, so still looking on changing the white header. But thoughts on less black site, it does look more on trend although looks better without original behind.  
Can you clarify a bit more.

<img width="1031" alt="blackGit" src="https://user-images.githubusercontent.com/20134338/106023183-7a7d0b00-60be-11eb-8588-6766b7afc15b.png">

**Comment by nanjizal** [comment]
background used... maybe the gradient corner is just to excite designers who love subtlity no one else can see especially with git black on! The current code seems to use a background.png... not ideal and probably could be really small if single color.
![gitGradbackground](https://user-images.githubusercontent.com/20134338/106024097-55d56300-60bf-11eb-95ec-f0ab345d4249.png)

**Comment by nanjizal** [comment]
0E141C and the grey base-color is 
//$color-base:                                                            #17bed2 !default;
$color-base:                                                            #353a41 !default;

**Comment by nanjizal** [comment]
Just so you can see what it looks like as you scroll up.
<img width="1031" alt="awayGreyWhite" src="https://user-images.githubusercontent.com/20134338/106025127-5de1d280-60c0-11eb-84ea-51f140922fa6.png">

**Comment by nanjizal** [comment]
Anyway when in this position, do you want the white areas to go grey or just to keep top to be more dark grey?

**Comment by nanjizal** [comment]
Ah found the header in saas.utils._colors
```Javascript
/* Page On Scroll */
@media (min-width: $screen-md-min) {
    .page-on-scroll {
        .header {
            .navbar {
                background: #cccccc;//$color-white;
```

**Comment by nanjizal** [comment]
Ok there is a bottom border and font text and they look to be moved around. There are atleast two places I can introduce a global variable in place of 'white' but not sure on the grey it looks a bit dull.  Other aspect is that the page white and the bounce top edge. This grey is just a github one, not right.
<img width="1002" alt="headerChangeAway" src="https://user-images.githubusercontent.com/20134338/106034553-f3825f80-60ca-11eb-8bf0-d55d39e5a7ae.png">

**Comment by nanjizal** [comment]
Guess the grey change looks too soft now ( especially when I change font and logo and the strip minimized section bar ).
