### ISSUE TITLE
Temporarily remove News section

### ISSUE THREAD

**Issue by rob-bateman** [awayfl/awayfl.org#4]
We don't have any news right now, and the current widget is not properly populated by content anyway, so it would be best to disable this for now

**Comment by nanjizal** [comment]
First look at Hexo so be gentle if the info is not suitable.

Hi News can be removed for later insertion:

1) By commenting out the news button from the menu.
aircv/source/_default_data/menu.yaml
```Javascript
- text: Home
  href: "#body"

#- text: News
#  href: "#news"

- text: Works
  href: "#works"

- text: About Us
  href: "#aboutus"

- text: Contact
  href: "#contact"

#- text: Blog
#  href: "/blog"

#- text: Acceso
#  href: "/login"

```

2 ) Commenting out experiance on the page.
aircv/layout/index.ejs
```Javascript
<%- partial('_partial/home/hero/index') %>
<%#- partial('_partial/home/experience/index') %>
<%- partial('_partial/home/portfolio/index') %>
<%- partial('_partial/home/about/index') %>
<%- partial('_partial/home/contact/index') %>
<%#- partial('_partial/home/products') %>
```

**Comment by nanjizal** [comment]
created pull request 
https://github.com/awayfl/awayfl.org/pull/5
for moment made change to a version I did not npm install so I was sure no other files would be modified, but probably this was me being over cautious.
